version: "3"
services:
  # service configuration for mongo database.
  mongo:
    # see https://hub.docker.com/_/mongo/
    image: mongo:4.0.9
    ports:
     - "27017:27017"
    volumes:
      - mongo-local:/data/db

# this is the name of volumes which persist.
volumes:
  mongo-local:
